#!/bin/sh
sleep 10
wmname=`wm_name`
if test "$wmname" = 'dwm'; then
	if [ ! -f "/tmp/dwm_conky.pid" ]; then
		(conky | while read LINE; do xsetroot -name " $LINE "; done) &
		echo $! > /tmp/dwm_conky.pid
	fi
fi
